### ISSUE TITLE
AttributeError: type object 'Solver' has no attribute 'requirements'

### ISSUE THREAD

**Issue by albanPi** [tomMoral/benchmark_classification#3]
## How to reproduce the error
I got *AttributeError: type object 'Solver' has no attribute 'requirements'* when I tried to launch a benchwark with XGBClassifier solver without installing in my conda environnement the package xgboost.

## Fixing the error
To fix it, I added a variable called `requirements` in the file of the solver causing this error (i.e `xgboost.py`). This variable must contain an one element list with the name of the solver's conda package (in this case it'll be `requirements = ["py-xgboost"]`).

**Comment by tomMoral** [comment]
This is now tracked in benchopt/benchopt#561.
